name: Hello World CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]


jobs:
  hello:
    runs-on: ubuntu-latest  # Операционная система для выполнения задания

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Клонирование репозитория

      - name: Set up C++ env
        run: sudo apt-get install g++  # Установка компилятора g++ (можно пропустить, если он предустановлен)

      - name: Compile test.cpp
        run: g++ -o test test.cpp  # Компиляция файла test.cpp
        
      - name: Run test
        run: ./test  # Запуск скомпилированного файла
