name: CI
on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up C++ environment
        run: sudo apt-get install g++

      - name: Build the project
        run: g++ -o my_app main.cpp

      - name: Run tests
        run: ./run_tests.sh
